#include "main.h"

CombatScene player_character;

const PROGMEM unsigned char message[] = "LOREM IPSUM ODOR AMET CONSECTETUER ADIPISCING ELIT SIT !ULTRICIES SOLLICITUDIN NEQUE VULPUTATE ARCU CRAS QUAM TEMPOR POSUERE NOSTRA MI DUI TEMPOR ODIO NATOQUE LIGULA CONGUE IMPERDIET MI SODALES ENIM HABITASSE ORCI PRAESENT NISL RISUS SODALES MOLESTIE TORTOR PRAESENT TINCIDUNT EUISMOD HENDRERIT MAXIMUS LOREM TEMPOR PRETIUM AMET EUISMOD PER CONGUE UT LAOREET AD APTENT AUCTOR LECTUS AUCTORDUI VELIT EST AC PULVINAR CONVALLIS ULLAMCORPER TORTOR CURABITUR VESTIBULUM VARIUS ADIPISCING ADIPISCING FEUGIAT PORTTITOR NUNC DIGNISSIM RHONCUS LEO VULPUTATE VEL METUS QUAM SUSPENDISSE RISUS HABITASSE CLASS URNA MONTES UT MOLLIS ALIQUET JUSTO CURSUS SIT FAUCIBUS POTENTI ORCI CURAE VEHICULA TINCIDUNT PARTURIENT SUSCIPIT NEC PARTURIENT MAURIS ADIPISCING RHONCUS VULPUTATE AENEAN ET SIT NETUS NEC NEQUE LACUS LIBERO CONUBIA HENDRERIT ERAT EGET MAGNA UT CONDIMENTUMLACUS ODIO ETIAM AUGUE PARTURIENT LACINIA FELIS LOBORTIS LIGULA CUBILIA ODIO AENEAN MAXIMUS SUSCIPIT QUISQUE IMPERDIET SED LACUS CUBILIA ULTRICES POSUERE LOBORTIS SENECTUS SUSCIPIT RISUS VULPUTATE SODALES DOLOR INTEGER FRINGILLA PER ELEMENTUM IMPERDIET PORTA LOREM CRAS VITAE HAC AUGUE HABITASSE DOLOR MAXIMUS AC MORBI INTERDUM METUS QUISQUE SUSCIPIT MORBI URNA FRINGILLA NISI FINIBUS NISL PHARETRA ERAT MOLESTIE POTENTI EGET PHASELLUS PRAESENT RIDICULUS CONVALLIS LIBERO NUNC ET NEQUE NON MAGNIS DOLORDIAM NUNC FUSCE DUIS VEHICULA CUBILIA VESTIBULUM UT MAGNA PORTA ALIQUAM LITORA DUIS NULLAM FACILISIS PULVINAR TELLUS INTERDUM PRIMIS MASSA SEM AENEAN PELLENTESQUE ALIQUET AENEAN FELIS TEMPUS DIAM ALIQUAM NAM CONUBIA SODALES ALIQUAM TINCIDUNT QUIS ALIQUAM SIT VEL CRAS AC APTENT ORNARE LACUS CONUBIA PENATIBUS MAXIMUS RISUS FACILISI ADIPISCING SAPIEN TURPIS MASSA LECTUS QUIS CLASS ELIT TORQUENT FERMENTUM FAUCIBUS CONUBIA PHASELLUS EGESTAS SIT INTERDUM ETIAM ALIQUET ULTRICES ANTE LUCTUS RUTRUM ADIPISCING AT HIMENAEOS PERTORQUENT ALIQUET HABITASSE DIGNISSIM TURPIS ETIAM IACULIS LOBORTIS SOCIOSQU INCEPTOS NOSTRA BLANDIT DIGNISSIM FELIS RUTRUM SAPIEN NATOQUE MONTES RUTRUM PER SOLLICITUDIN ORNARE RISUS ID HABITANT CONVALLIS SEM MATTIS SAGITTIS RISUS FEUGIAT IPSUM NEC LACUS COMMODO MAURIS LAOREET PORTA HAC AENEAN AC ACCUMSAN FERMENTUM LAOREET TURPIS AC INCE!PTOS JUSTO HABITANT PURUS PURUS ANTE AENEAN CONUBIA LITORA CLASS ENIM IACULIS INTEGER QUAM VEHICULA EUISMOD ARCU NAM PARTURIENT FAUCIBUSAT DICTUMST POTENTI DONEC FAMES EGET PER CUBILIA MUS NEC ULLAMCORPER A PRIMIS DUI DIGNISSIM MAECENAS DOLOR LECTUS? QUAM SOLLICITUDIN SIT PRAESENT EX AD DIGNISSIM IN PURUS NAM MOLLIS RHONCUS ORCI ORNARE PRAESENT INCEPTOS DOLOR DIGNISSIM ELIT VOLUTPAT SEMPER PRIMIS FUSCE FINIBUS CURAE CONVALLIS VESTIBULUM SCELERISQUE PULVINAR PELLENTESQUE PROIN DONEC NULLAM MAECENAS IN TORQUENT HIMENAEOS SUSPENDISSE FEUGIAT RIDICULUS INCEPTOS NUNC MOLLIS NEQUE VIVERRA A NULLA MAGNIS CRAS MASSA AD LIGULA PULVINAR VITAE SOLLICITUDIN ELEIFEND MI VITAE PELLENTESQUE EUISMOD TEMPOR MASSAMOLLIS MATTIS IN SEMPER GRAVIDA VITAE MONTES RHONCUS VESTIBULUM CUBILIA CUBILIA MAURIS COMMODO HAC ELIT DAPIBUS IMPERDIET APTENT ID EUISMOD PER ENIM VEHICULA HABITASSE AMET ERAT ID SODALES QUISQUE TRISTIQUE FACILISIS HABITANT NETUS EGESTAS PULVINAR MALESUADA MAGNIS DONEC AD DUI HIMENAEOS MAGNIS MAGNA LACINIA DAPIBUS VEL SODALES MALESUADA VENENATIS BLANDIT PURUS MAECENAS GRAVIDA DAPIBUS EU DONEC ULTRICES HAC JUSTO PORTTITOR UT VEL AENEAN ADIPISCING NOSTRA QUIS NEQUE VULPUTATE HABITASSE EFFICITUR PENATIBUS ALIQUAM SUSPENDISSE MAGNA HIMENAEOS MAURISRISUS QUISQUE VIVAMUS VITAE PULVINAR ELIT PER SODALES CONGUE AENEAN MONTES SODALES AD NETUS PLATEA SAPIEN CUBILIA LITORA MAXIMUS FEUGIAT CRAS SED RUTRUM FACILISIS SEMPER VESTIBULUM ORCI DAPIBUS PURUS SEM DIGNISSIM MAGNA TORQUENT SEMPER PRIMIS HABITANT LUCTUS TURPIS MAXIMUS LITORA RHONCUS APTENT NAM NOSTRA ELEIFEND FACILISI DUIS ARCU JUSTO MASSA EU POTENTI RISUS EGET NUNC FUSCE NOSTRA ARCU ENIM EST MAURIS LACUSNULLAM MATTIS AUGUE VOLUTPAT CONVALLIS HENDRERIT ANTE LOBORTIS ULLAMCORPER PROIN VOLUTPAT ORNARE TEMPOR ELEIFEND ELIT SAPIEN AT SUSPENDISSE VESTIBULUM MOLLIS URNA DICTUM SCELERISQUE DAPIBUS PULVINAR? LEO DAPIBUS DUIS RUTRUM NAM ULTRICES ENIM UT ERAT DUIS LUCTUS CONUBIA PRETIUM SEMPER CURAE NIBH VEL NASCETUR RUTRUM NETUS HIMENAEOS TELLUS SED ETIAM UT SODALES ORNARE NETUS SED EUISMOD MUS NEC? AMET AD VOLUTPAT ULTRICES EU FEUGIAT ADIPISCING PENATIBUS EFFICITUR CURSUS ALIQUAM GRAVIDA UT IACULISULLAMCORPER ULTRICES MONTES EUISMOD POTENTI TEMPUS NEQUE PORTTITOR SODALES QUAM PELLENTESQUE IPSUM ID VESTIBULUM URNA ERAT CONSEQUAT DIS DOLOR PLATEA INCEPTOS ETIAM LIBERO NEQUE PHARETRA FINIBUS COMMODO NON FERMENTUM QUAM ORCI TORTOR ADIPISCING LIGULA EX DICTUMST VOLUTPAT CURSUS MI CURSUS VENENATIS PURUS ETIAM IPSUM EGESTAS BLANDIT HIMENAEOS QUIS PENATIBUS IN IMPERDIET SOCIOSQU FEUGIAT CONGUE EX PLATEA TORQUENT TURPIS MAECENAS NISLURNA POTENTI DICTUM CONGUE RHONCUS LACINIA PENATIBUS SOCIOSQU FERMENTUM RIDICULUS FELIS VIVERRA MAECENAS JUS!TO VESTIBULUM METUS CURABITUR PRAESENT SOLLICITUDIN NON NIBH POSUERE? FUSCE SAPIEN ALIQUAM FEUGIAT INCEPTOS CURAE LECTUS VARIUS LACUS INCEPTOS LEO TORTOR VULPUTATE SCELERISQUE GRAVIDA EGESTAS AT PULVINAR DIGNISSIM NEQUE SEM MAURIS PROIN ELEMENTUM MOLLIS ULTRICIES IN LACINIA PROIN VELIT SIT EGET SAGITTIS VESTIBULUM VIVERRA VEHICULA NIBH LECTUS ANTE FEUGIAT EX VELITVESTIBULUM FAUCIBUS MONTES ALIQUAM MUS PORTA FAUCIBUS NON ID TRISTIQUE ANTE DAPIBUS SEMPER TRISTIQUE ENIM CUBILIA NEQUE DAPIBUS LEO SOLLICITUDIN DIS NON QUISQUE DIAM NETUS NATOQUE DOLOR TELLUS PURUS FACILISI RHONCUS SODALES? NOSTRA URNA LIBERO ULTRICES AT POTENTI CONGUE ELEIFEND AD ADIPISCING RUTRUM PROIN PLACERAT CONSEQUAT INTERDUM EUISMOD NOSTRA PORTTITORSCELERISQUE NEQUE MAECENAS LEO LAOREET ID TEMPOR TEMPUS PLACERAT SUSPENDISSE QUAM SEM SOCIOSQU ARCU MI VENENATIS COMMODO PLACERAT JUSTO RHONCUS MAGNIS MAGNIS METUS VEL IMPERDIET NOSTRA CLASS PRAESENT CURAE PRETIUM PLACERAT TORTOR DICTUM SODALES NATOQUE MALESUADA TURPIS INTERDUM PARTURIENT NULLAM A EUISMOD IMPERDIET FELIS ID ULLAMCORPER SEMPER RHONCUS CONDIMENTUM MI EU LITORA TACITI LAOREET MAGNA NASCETUR CLASS EST PORTTITOR NISI LOBORTIS FEUGIAT NEC ELEMENTUM ULTRICES PULVINAR UT AUCTOR NASCETURETIAM NUNC LIGULA NATOQUE DICTUMST VULPUTATE PULVINAR ENIM LEO IPSUM MI PHASELLUS CUBILIA DUIS SODALES CONVALLIS URNA MAECENAS TINCIDUNT PER ENIM DICTUM IACULIS RISUS HAC NULLA NEC DUIS DAPIBUS ELIT IPSUM MUS METUS VOLUTPAT PULVINAR POTENTI APTENT ORCI AT CLASS DIAM MAXIMUS DIS VELIT EU PROIN UT ELEIFEND TRISTIQUE HIMENAEOS CLASS VOLUTPAT QUIS ODIO NISL HAC ULLAMCORPER SUSPENDISSE BLANDIT PORTA FINIBUS FAUCIBUS SEM ALIQUAM SED VESTIBULUM MAURIS CONDIMENTUM FACILISIS LOBORTIS SED SENECTUS PENATIBUS ID ID AD?NATOQUE INTERDUM CUBILIA ELEMENTUM METUS LACUS LIGULA EFFICITUR ARCU FERMENTUM QUAM MOLLIS FUSCE VOLUTPAT PLATEA NULLA FAMES IMPERDIET TORQUENT CONVALLIS CRAS LACINIA VARIUS ULTRICES ID VOLUTPAT HIMENAEOS SOLLICITUDIN PULVINAR HENDRERIT MAGNA SODALES NOSTRA FAUCIBUS SCELERISQUE AUCTOR SEMPER INTEGER NISI RIDICULUS TEMPOR EFFICITUR NETUS EUISMOD TORQUENT CONDIMENTUM ELIT ORCI ENIM LOBOR!TIS EUISMOD NAM NEC DIS NISL EGESTAS VEHICULA NEQUE PHARETRA CONSECTETUR NON ARCU? LEO MASSA LOBORTIS AT ELEIFEND SUSPENDISSEPRETIUM METUS FACILISI EROS RIDICULUS ULLAMCORPER ELIT TORTOR NULLA MAECENAS LUCTUS UT MASSA NON VEL PORTA ID QUIS INTERDUM POTENTI INTERDUM VELIT PRETIUM DIGNISSIM TINCIDUNT RUTRUM PORTA LAOREET NISL SIT VITAE IPSUM PLATEA FERMENTUM CONVALLIS EFFICITUR ELEMENTUM VOLUTPAT LOBORTIS NAM ID TORTOR VULPUTATE PULVINAR TRISTIQUE PRIMIS DOLOR RHONCUS SEM NOSTRA EST NIBH DUI PLATEA TORTORURNA ELEIFEND DIAM ANTE NISL PORTTITOR LEO ALIQUET PORTTITOR MOLESTIE ORCI MASSA ALIQUET SUSCIPIT LUCTUS FINIBUS MAXIMUS MOLLIS EGET LAOREET TACITI MI DUI DIAM AD DUI CONVALLIS LACUS VULPUTATE DICTUM METUS CUBILIA ET SODALES EU TEMPOR PRETIUM MAURIS POSUERE IN ID RU!TRUM INTEGER NISL DICTUM POTENTI ERAT SEMPER ELEMENTUM URNA EFFICITUR SCELERISQUE MOLLIS CLASS NETUS FAUCIBUS SUSPENDISSE SOLLICITUDIN DUIS INTERDUM";


void setup() {
  Serial.begin(9600);
  Wire.begin();
  delay(1000);
  DisplaySetupCommands();
  MoveCursor(0x00, 0x00);
  FillScreen(0x00);
}

void loop() {

  //MoveCursor(0x00, 0x00);
  //FillScreen(0xA5);

  /* Proof of concept / able to expect correct display  
    MoveCursor(0x00, 0x00);
    PushToScreen(0x1E);
    PushToScreen(0x05);
    PushToScreen(0x05);
    PushToScreen(0x05);
    PushToScreen(0x1E);
    MoveCursor(0x01, 0x00);
    PushToScreen(B00011110);
    PushToScreen(B00000101);
    PushToScreen(B00000101);
    PushToScreen(B00000101);
    PushToScreen(B00011110); */

  delay(1000);
  MoveCursor(0x00, 0x00);
  profileThisStart();
  TextPusherArray(message, sizeof(message));
  profileThisEnd(); 
  
/*  profileThisStart();
  TextPusher(message, sizeof(message));
  profileThisEnd();
  */

  player_character.DisplayHealth();
}
